- name: Set iptabes Policies
  hosts: all
  tasks:
   - name: Set ACCEPT Policy for INPUT
      iptables:
        chain: INPUT
        policy: ACCEPT

   - name: Set ACCEPT Policy for FORWARD
      iptables:
        chain: FORWARD
        policy: ACCEPT

   - name: Set ACCEPT Policy for OUTPUT
      iptables:
        chain: OUTPUT
        policy: ACCEPT

