---

OGS: "abc"
RAM: "512"
DISK: "10"
CPU: "10"
H-IP: "10.10.0.1"
V-IP: "10.10.0.2"
PROVIDER: "Vultr"

REGION: "Toronto"
VULTR_API_KEY: "UT4GRA7FCLKMZ5KCZV534Q3PEQFCHD33AGIQ"
VULTR_PLAN_ID: "vc2-1c-0.5gb"