
---
all:
  vars:
    ansible_user: root
  children: 
    hplmn:  
      hosts:
        hplmn_node_1: 
          ansible_host: 149.248.54.132
        
    vplmn:  
      hosts:
        vplmn_node_1: 
          ansible_host: 155.138.155.120
        
    topssim:  
      hosts:
        topssim_node_1: 
          ansible_host: 216.128.184.104
        
